// <auto-generated />
using BT_CodeFirst_CafeManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Quản_lý_Phòng_Gym.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quan_Ly_Phong_Gym.Models.GoiTap", b =>
                {
                    b.Property<int>("MaGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoi"));

                    b.Property<double>("GiaTien")
                        .HasColumnType("float");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGoi");

                    b.ToTable("GoiTaps");
                });

            modelBuilder.Entity("Quan_Ly_Phong_Gym.Models.HoiVien", b =>
                {
                    b.Property<int>("MaHoiVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoiVien"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGoi")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoiVien");

                    b.HasIndex("MaGoi");

                    b.ToTable("HoiViens");
                });

            modelBuilder.Entity("Quan_Ly_Phong_Gym.Models.HoiVien", b =>
                {
                    b.HasOne("Quan_Ly_Phong_Gym.Models.GoiTap", "GoiTap")
                        .WithMany("HoiViens")
                        .HasForeignKey("MaGoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");
                });

            modelBuilder.Entity("Quan_Ly_Phong_Gym.Models.GoiTap", b =>
                {
                    b.Navigation("HoiViens");
                });
#pragma warning restore 612, 618
        }
    }
}
